---
kind: pipeline
type: kubernetes
name: unifi

steps:
  - name: bobo
    image: crazy-max/ghaction-docker-buildx@v1
    commmands:
      - ls -l
      - docker buildx build  --tag lehtux/unifi:latest  --platform linux/amd64,linux/arm/v7,linux/arm64 .

